#!/usr/bin/env ruby
#^syntax detection
 
site 'http://community.opscode.com/api/v1'
 
cookbook "apt"
cookbook "java"
cookbook "git"
cookbook "build-essential"
cookbook "rvm"
cookbook "mysql"
cookbook "maven"
